---
title: "Progress Memo 2"
subtitle: |
  | Final Project 
  | Data Science 2 with R (STAT 301-2)
author: "Louise Oh"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false
  message: false

from: markdown+emoji 
reference-location: margin
citation-location: margin
---

::: {.callout-tip icon=false}
## Github Repo Link

[https://github.com/stat301-2-2024-winter/final-project-2-louiseoh2025.git](https://github.com/stat301-2-2024-winter/final-project-2-louiseoh2025.git)

:::

## Dataset Overview

The Mental Health In Pregnancy During COVID-19 Dataset^[Mental Health In Pregnancy During COVID-19 --- [https://www.kaggle.com/datasets/yeganehbavafa/mental-health-in-the-pregnancy-during-the-covid-19](https://www.kaggle.com/datasets/yeganehbavafa/mental-health-in-the-pregnancy-during-the-covid-19)] is aimed to understand the impact of COVID-19-related stresses on pregnant individuals and their infants and collected survey-based data across Canada as part of the Pregnancy during the COVID-19 Pandemic (PdP) project. This survey-based data allows for insights that can inform targeted interventions and support strategies to address the impact of COVID-19-related stresses on maternal and infant health.

::: {.callout-note icon="false"}
## Prediction Research Objective 

The goal is regression, specifically what the weight of the child at birth will be based on the mother's biological and psychological factors in pregnancy during a pandemic.

:::

## Target Variable

The target variable is `birth_weight`. This is a numerical variable in the form of double. The histogram below shows a unimodal distribution that is slightly skewed toward the left, but still nearly symmetric. The distribution looks nearly normal with outliers on both ends, but slightly more on the lower end, of the weight distribution. The original data has a distribution closer to a normal distribution compared to when it is transformed in some way, so no transformation is necessary.

## 1. Data Splitting and Resampling

The cleaned pregnancy data was split into training (80%) and testing (20%) datasets. The split was stratified by the target variable, `birth_weight`. Repeated V-fold cross-validation with 5 folds and 3 repeats are performed on the training data. This technique randomly and repeatedly splits the data into V subsets of approximately equal size for training and validation. This provides a robust estimate of model performance and V sets of performance metrics. With this particular setup, each model will be trained and evaluated 15 times, covering various combinations of training and validation data. This is better than simply fitting and testing the models because it prevents overfitting and improves parameter and model accuracies by taking the uncertainty into account. See 1_*.R scripts for codes. 


## 2. Recipes

There are two recipes used for the models. The first recipe is a standard recipe created with the following steps: filter out variables have have zero variance (step_zv), center and scale all predictors (step_normalize), one-hot encode all categorical predictors (step_dummy), and remove uniqueID and date (step_rm). This is the most basic recipe similar to a kitchen sink recipe. The recipe was prepped and baked, and seemed to work. 

The second recipe is a more customized recipe with revised and additional steps after a simple EDA: only remove unique ID (step_rm), add interaction terms between the threaten_baby_ variables and between the anxiety and depression levels which were related to each other (step_interact), specify delivery date as date (step_date). The recipe was prepped and baked, and seemed to work. See 2_*.R scripts for codes. 

basic recipe:

- Zero variance filter on: all_predictors()

- Centering and scaling for: all_numeric_predictors()

- Dummy variables from: all_nominal_predictors()

- Variables removed: delivery_date, osf_id

customized recipe:

- Zero variance filter on: all_predictors()

- Centering and scaling for: all_numeric_predictors()

- Dummy variables from: all_nominal_predictors()

- Variables removed: osf_id

- Interactions with: threaten_baby_danger:threaten_baby_harm

- Interactions with: promis_anxiety:postnatal_depression

- Date features from: delivery_date


## 3. Models

There is a baseline linear regression model which uses the standard recipe. Six additional models are created for the prediction problem: ordinary linear regression, lasso regression, ridge regression, random forest, k-nearest neighbor, and boosted tree. The standard recipe was used to fit the lasso regression, ridge regression, and the boosted tree models. The customized recipe was used to fit the ordinary linear regression, random forest, and k-nearest neighbor models. The random forest, k-nearest neighbor, and boosted tree models were tuned using `tune_grid()`. All models seemed to run properly. See 3_*.R scripts for codes. 


## 4. Model Analysis (plan)

So far, the random forest model seems to work best based on the RMSE and its SE. However, the customized recipe and the models could be further refined before performing the model analyses. For the model analyses, more variety of measures could be compared. RMSE, RSQ, MSE, and other metrics will be used. A best model will be chosen, and this model will be fitted using the whole training dataset instead of the folds. Afterwards, a final model analysis will be performed on this model, which will be the final model used to predict the baby's birth weight for this project. 


## Timeline

- February 26: complete basic requirements for this project (2 recipes and 6 model types)
- March 1: perform model analyses and finalize the recipes and model types
- March 3: write a draft of the final report and have any questions answered by Prof/TAs
- March 5: write the executive summary and update github repo and README documents
- March 6: proofread and submit final project
